### ISSUE TITLE
Sharing single INI file amongst cluster?

### ISSUE THREAD

**Issue by Avuja** [r15ch13/arkcluster#8]
Have successfully stood up a cluster of several servers and am looking for the best way of migrating my settings from previous installs to this new containerized setup.

What's the best practice for altering the Game.ini and GameUserSettings.ini across all servers within a cluster?

Does it need to be done individually on each server volume?

Do they get overwritten each time docker compose is ran?

Should I edit a template instead? or should I be using the arkmanager for settings like tame speed and such?

**Comment by r15ch13** [comment]
You have to manually copy `Game.ini` and `GameUserSettings.ini` to every server volume.
Arkmanager only overwrites some settings like passwords and ports set in the `arkmanager.cfg`.

You could add separate config volume and point `arkGameUserSettingsIniFile` and `arkGameIniFile` to it. Haven't tested that.
Don't know why, because I have the same problem as you :grin:
